-- Script para poblar la tabla de libros con caracteres especiales
-- Configurando encoding UTF-8

SET client_encoding = 'UTF8';

INSERT INTO libros (titulo, autor, editorial, genero, precio, disponibilidad, estado, "createdAt", "updatedAt") VALUES
('Cien años de soledad', 'Gabriel García Márquez', 'Sudamericana', 'Realismo mágico', 2500, true, 'activo', NOW(), NOW()),
('Don Quijote de la Mancha', 'Miguel de Cervantes', 'Francisco de Robles', 'Novela', 1800, true, 'activo', NOW(), NOW()),
('1984', 'George Orwell', 'Secker & Warburg', 'Distopía', 2200, true, 'activo', NOW(), NOW()),
('El amor en los tiempos del cólera', 'Gabriel García Márquez', 'Oveja Negra', 'Romance', 2300, false, 'activo', NOW(), NOW()),
('Rayuela', 'Julio Cortázar', 'Sudamericana', 'Ficción experimental', 2000, true, 'activo', NOW(), NOW()),
('La casa de los espíritus', 'Isabel Allende', 'Plaza & Janés', 'Realismo mágico', 2100, true, 'activo', NOW(), NOW()),
('Orgullo y prejuicio', 'Jane Austen', 'T. Egerton', 'Romance', 1900, true, 'activo', NOW(), NOW()),
('El principito', 'Antoine de Saint-Exupéry', 'Reynal & Hitchcock', 'Fábula', 1500, true, 'activo', NOW(), NOW()),
('Matar un ruiseñor', 'Harper Lee', 'J. B. Lippincott & Co.', 'Ficción', 2000, false, 'activo', NOW(), NOW()),
('El gran Gatsby', 'F. Scott Fitzgerald', 'Charles Scribner''s Sons', 'Ficción', 1800, true, 'activo', NOW(), NOW()),
('Crimen y castigo', 'Fiódor Dostoyevski', 'El Mensajero Ruso', 'Novela psicológica', 2400, true, 'activo', NOW(), NOW()),
('Los Miserables', 'Victor Hugo', 'A. Lacroix, Verboeckhoven & Cie', 'Novela histórica', 2800, false, 'activo', NOW(), NOW()),
('Ulises', 'James Joyce', 'Sylvia Beach', 'Modernismo', 3000, true, 'activo', NOW(), NOW()),
('En busca del tiempo perdido', 'Marcel Proust', 'Grasset', 'Ficción autobiográfica', 3500, false, 'activo', NOW(), NOW()),
('El guardián entre el centeno', 'J.D. Salinger', 'Little, Brown and Company', 'Ficción', 1900, true, 'activo', NOW(), NOW()),
('Lolita', 'Vladimir Nabokov', 'Olympia Press', 'Ficción', 2100, true, 'activo', NOW(), NOW()),
('Fahrenheit 451', 'Ray Bradbury', 'Ballantine Books', 'Ciencia ficción', 1800, true, 'activo', NOW(), NOW()),
('El señor de las moscas', 'William Golding', 'Faber & Faber', 'Ficción', 1700, false, 'activo', NOW(), NOW()),
('Un mundo feliz', 'Aldous Huxley', 'Chatto & Windus', 'Distopía', 2000, true, 'activo', NOW(), NOW()),
('Anna Karenina', 'León Tolstói', 'El Mensajero Ruso', 'Realismo', 2600, true, 'activo', NOW(), NOW()),
('La Odisea', 'Homero', 'Antigua Grecia', 'Épica', 1600, true, 'activo', NOW(), NOW()),
('Hamlet', 'William Shakespeare', 'Nicholas Ling', 'Drama', 1400, true, 'activo', NOW(), NOW()),
('El proceso', 'Franz Kafka', 'Verlag Die Schmiede', 'Ficción kafkiana', 1900, false, 'activo', NOW(), NOW()),
('El extranjero', 'Albert Camus', 'Gallimard', 'Existencialismo', 1700, true, 'activo', NOW(), NOW()),
('La metamorfosis', 'Franz Kafka', 'Kurt Wolff Verlag', 'Ficción kafkiana', 1500, true, 'activo', NOW(), NOW()),
('Moby Dick', 'Herman Melville', 'Richard Bentley', 'Aventura', 2200, true, 'activo', NOW(), NOW()),
('Guerra y paz', 'León Tolstói', 'El Mensajero Ruso', 'Novela histórica', 2900, false, 'activo', NOW(), NOW()),
('El retrato de Dorian Gray', 'Oscar Wilde', 'Ward, Lock & Co.', 'Ficción gótica', 1800, true, 'activo', NOW(), NOW()),
('Jane Eyre', 'Charlotte Brontë', 'Smith, Elder & Co.', 'Romance gótico', 1900, true, 'activo', NOW(), NOW()),
('Drácula', 'Bram Stoker', 'Archibald Constable', 'Terror gótico', 2000, false, 'activo', NOW(), NOW()),
('Frankenstein', 'Mary Shelley', 'Lackington, Hughes', 'Ciencia ficción gótica', 1800, true, 'activo', NOW(), NOW()),
('El conde de Montecristo', 'Alexandre Dumas', 'Journal des Débats', 'Aventura', 2400, true, 'activo', NOW(), NOW()),
('Los tres mosqueteros', 'Alexandre Dumas', 'Le Siècle', 'Aventura histórica', 2100, true, 'activo', NOW(), NOW()),
('Robinson Crusoe', 'Daniel Defoe', 'William Taylor', 'Aventura', 1700, false, 'activo', NOW(), NOW()),
('Las aventuras de Tom Sawyer', 'Mark Twain', 'American Publishing Company', 'Aventura juvenil', 1600, true, 'activo', NOW(), NOW()),
('Alicia en el país de las maravillas', 'Lewis Carroll', 'Macmillan', 'Fantasía infantil', 1400, true, 'activo', NOW(), NOW()),
('El libro de la selva', 'Rudyard Kipling', 'Macmillan', 'Literatura infantil', 1500, true, 'activo', NOW(), NOW()),
('Peter Pan', 'J.M. Barrie', 'Hodder & Stoughton', 'Fantasía infantil', 1300, false, 'activo', NOW(), NOW()),
('El hobbit', 'J.R.R. Tolkien', 'George Allen & Unwin', 'Fantasía épica', 2200, true, 'activo', NOW(), NOW()),
('El señor de los anillos', 'J.R.R. Tolkien', 'George Allen & Unwin', 'Fantasía épica', 3200, true, 'activo', NOW(), NOW()),
('Crónicas de Narnia', 'C.S. Lewis', 'Geoffrey Bles', 'Fantasía infantil', 2000, true, 'activo', NOW(), NOW()),
('Harry Potter y la piedra filosofal', 'J.K. Rowling', 'Bloomsbury', 'Fantasía juvenil', 1800, false, 'activo', NOW(), NOW()),
('El nombre del viento', 'Patrick Rothfuss', 'DAW Books', 'Fantasía épica', 2300, true, 'activo', NOW(), NOW()),
('Juego de tronos', 'George R.R. Martin', 'Bantam Spectra', 'Fantasía épica', 2500, true, 'activo', NOW(), NOW()),
('Neuromante', 'William Gibson', 'Ace Books', 'Cyberpunk', 2000, false, 'activo', NOW(), NOW()),
('Fundación', 'Isaac Asimov', 'Gnome Press', 'Ciencia ficción', 2100, true, 'activo', NOW(), NOW()),
('Dune', 'Frank Herbert', 'Chilton Books', 'Ciencia ficción', 2600, true, 'activo', NOW(), NOW()),
('2001: Una odisea del espacio', 'Arthur C. Clarke', 'Hutchinson', 'Ciencia ficción', 1900, true, 'activo', NOW(), NOW()),
('Yo, robot', 'Isaac Asimov', 'Gnome Press', 'Ciencia ficción', 1800, false, 'activo', NOW(), NOW()),
('El fin de la eternidad', 'Isaac Asimov', 'Doubleday', 'Ciencia ficción', 1900, true, 'activo', NOW(), NOW()),
('Contacto', 'Carl Sagan', 'Simon & Schuster', 'Ciencia ficción', 2000, true, 'activo', NOW(), NOW());